### ISSUE TITLE
Add npm publish to GitHub Actions

### ISSUE THREAD

**Issue by taichunmin** [myfreeweb/eslint-plugin-pug#18]
I have add npm publish to GitHub Actions. But it require a secret `NPM_TOKEN` to run. Could @valpackett add that for me?

**Comment by valpackett** [comment]
ugh, npm does not support limiting access tokens to one package, I'll have to make a new user for this..

Also, I don't think the current configuration is correct, as it would attempt to `npm publish` any push to `master` (which btw I'd like to rename to match my other projects). Only version bumps (git tags) should be published! Otherwise it would probably error out saying this version is already published.

**Comment by taichunmin** [comment]
The GitHub Actions `JS-DevTools/npm-publish` only publishes if the version number in `package.json` differs from the latest on NPM.

Btw, a new user to generate npm token is a good idea!

**Comment by valpackett** [comment]
Should be set up now :tada:

**Comment by taichunmin** [comment]
Thanks!
